# Generated by Django 4.2.16 on 2024-11-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
